# Generated by Django 5.2.5 on 2025-09-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identification_number',
            field=models.CharField(blank=True, help_text='National ID or other identification number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant'), ('admin', 'Admin')], default='tenant', help_text='User role (landlord, tenant, or admin)', max_length=20),
        ),
    ]
